/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__robotpy_sim_core
#define __PYX_HAVE__robotpy_sim_core


#ifndef __PYX_HAVE_API__robotpy_sim_core

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void tick_robot(int __pyx_skip_dispatch);
__PYX_EXTERN_C void set_robot_mode_impl(PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *get_hal_data(void);
__PYX_EXTERN_C PyObject *get_dict_in_hal_data(char *, int);
__PYX_EXTERN_C void set_joystick_axis_impl(int, int, float);
__PYX_EXTERN_C void set_joystick_button_impl(int, int, PyObject *);
__PYX_EXTERN_C PyObject *load_robot_class(PyObject *);
__PYX_EXTERN_C void initialize_robot(PyObject *);

#endif /* !__PYX_HAVE_API__robotpy_sim_core */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initrobotpy_sim_core(void);
#else
PyMODINIT_FUNC PyInit_robotpy_sim_core(void);
#endif

#endif /* !__PYX_HAVE__robotpy_sim_core */
